require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'mosh' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'react-native-orientation-locker', :path => '../node_modules/react-native-orientation-locker'

  pod 'react-native-webview', :path => '../node_modules/react-native-webview'

  pod 'RNSketchCanvas', :path => '../node_modules/@terrylinla/react-native-sketch-canvas'

  pod 'react-native-slider', :path => '../node_modules/@react-native-community/slider'

  target 'moshTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'mosh-tvOS' do
  # Pods for mosh-tvOS

  target 'mosh-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
